name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2023-01-16
version: '10.0.0+68-dev'
project: 'drupal'
datestamp: 1673887651
