name: Composer Updates

on:
  schedule:
    - cron: "0 11 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check for updates
        run: composer outdated
        id: composer_updates
      - name: Create pull request
        if: steps.composer_updates.outcome == 'success'
        uses: peter-evans/create-pull-request@v3.11.0
        with:
          title: 'Composer updates'
          branch: updates
          commit-message: 'Auto update dependencies'
          delete-branch: true
